### ISSUE TITLE
When gene not found, geneinfo server dies.  

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#95]
How to reproduce:

http://geneinfo.iobio.io/api/gene/LA16c-4G1.3

If gene LA16c-4G1.3, the server dies...

Need to modifiy geneinfo code so that error is handled and message is returned.

**Comment by tonydisera** [comment]
Server log - 

/home/iobio/iobio/node_modules/sqlite3/lib/trace.js:28
                    throw err;
                          ^
TypeError: Cannot read property 'transcripts' of undefined
    at Statement.<anonymous> (/home/iobio/iobio/services/geneInfoServer.js:25:46)
--> in Database#all('SELECT * from genes where gene_name="LA16C-4G1.3"', [Function])
    at /home/iobio/iobio/services/geneInfoServer.js:23:6
    at Layer.handle [as handle_request] (/home/iobio/iobio/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/iobio/iobio/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/iobio/iobio/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/iobio/iobio/node_modules/express/lib/router/layer.js:95:5)
    at /home/iobio/iobio/node_modules/express/lib/router/index.js:277:22
    at param (/home/iobio/iobio/node_modules/express/lib/router/index.js:349:14)
    at param (/home/iobio/iobio/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/iobio/iobio/node_modules/express/lib/router/index.js:410:3)
error: Forever detected script exited with code: 8
error: Script restart attempt #1
Example app listening at http://0.0.0.0:8000

**Comment by tonydisera** [comment]
Fixed.  Waiting to push changes to Chase's github repository.
